// <auto-generated />
namespace SportLoto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequireDrawingIdInMainFond : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequireDrawingIdInMainFond));
        
        string IMigrationMetadata.Id
        {
            get { return "201605221051479_RequireDrawingIdInMainFond"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
